### ISSUE TITLE
1.5 Dataset: CLIP embeddings

### ISSUE THREAD

**Issue by karynaur** [BetaLabs-IIITKottayam/supreme-CLIP#2]
<b>Task:</b>
1. Use the colab notebook from #1 to retrive images as mentioned in `README.md` file in `data/` dir to retrive images.
2. Get [CLIP embeddings](https://github.com/openai/CLIP) of all the images and store it in a JSON file named `data.json`.
3. Give steps to load the json file and retrive the CLIP embeddings in `data/README.md`
4. Upload the colab notebook along with the `data.json` file

<b>JSON Format:</b>
{
   "image_id" : Int: Unsplash Image ID
   "image_url" : URL: image permalink
   "emb" : Pytorch Tensor size(1x512): CLIP Image embedding
   "tags" : array of String: Unsplash tags
}

<b>Resources:</b>
1. CLIP [github repo](https://github.com/openai/CLIP)

**Comment by nikhil9302** [comment]
can do this one

**Comment by karynaur** [comment]
assigned!

**Comment by Abhijit25Mishra** [comment]
@nikhil9302 I would like to help out ! Let me know if you need any help!

**Comment by adityagi02** [comment]
I'm collaborating with @nikhil9302 on this issue, do assign me here also
